title: MecaChek - Inspection mécanique mobile
short_title: MecaChek
description: Inspection mécanique mobile pré-achat avec rapport PDF sur place à Québec et dans la région
baseurl: "/Site-web-MecaChek"
url: ""
lang: fr

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
